### ISSUE TITLE
TransitNodeRoutingShortestPath performComputation

### ISSUE THREAD

**Issue by mbasa** [jgrapht/jgrapht#1040]
```
 * JGraphT version: 1.5.1-SNAPSHOT
 * Java version (java -version)/platform:  jdk11
```

**Issue**
A call to prerformComputation consumes over 350% of CPU and lasts over 3 hours. The process was terminated on the 3rd hour.

**Steps to reproduce (small coding example)**
```
private static TransitNodeRoutingShortestPath<Integer, 
        LabeledWeightedEdge> tnrsp = null;

ThreadPoolExecutor executor = 
                        (ThreadPoolExecutor) Executors.newFixedThreadPool(3);          

tnrsp = new TransitNodeRoutingShortestPath<Integer, 
                    LabeledWeightedEdge>(defaultGraph,executor);

tnrsp.performPrecomputation();
```
**Expected behaviour**

**Other information**
Included is the CSV file of the graph used. 

[output.csv.zip](https://github.com/jgrapht/jgrapht/files/5979476/output.csv.zip)

**Comment by jsichi** [comment]
@SChudakov can you take a look?

**Comment by mbasa** [comment]
Hello, what's the status of this issue? I can do testing if needed.

**Comment by SChudakov** [comment]
Hi, @mbasa, I will have a look at it later this week.

**Comment by SChudakov** [comment]
Sorry for the late response. I performed testing and here are the results:

This is not a bug, since the execution does not freeze. The JVM needs a lot of memory to compute the TNR in this case. I`ve used 12GB of ram as a JVM and for me the execution slowed down at the stage of computing the locality filter for the TNR. 

I would suggest you should consider following possibilities:

- make sure you are providing enought RAM space for your JVM
- using another algorithm (Contraction hierarchy provides very fast shortest path computation time)
- testing the TNR on a smaller graph

I`ve used following code to test your use case:

```{java}
package org.jgrapht._trials;

import org.jgrapht.Graph;
import org.jgrapht.Graphs;
import org.jgrapht.alg.shortestpath.TransitNodeRoutingShortestPath;
import org.jgrapht.graph.DefaultDirectedWeightedGraph;
import org.jgrapht.graph.DefaultUndirectedWeightedGraph;
import org.jgrapht.graph.DefaultWeightedEdge;
import org.jgrapht.util.ConcurrencyUtil;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.concurrent.ThreadPoolExecutor;

public class Main {
    public static void main(String[] args) throws IOException {
        System.out.println(Runtime.getRuntime().freeMemory()/1048576);
        long start = System.currentTimeMillis();
        Graph<Integer, DefaultWeightedEdge> graph = readGraph();

        ThreadPoolExecutor executor = ConcurrencyUtil.createThreadPoolExecutor(10);
        TransitNodeRoutingShortestPath<Integer, DefaultWeightedEdge> tnrsp
                = new TransitNodeRoutingShortestPath<>(graph, executor);
        tnrsp.performPrecomputation();
        long end = System.currentTimeMillis();
        System.out.println("execution took: " + ((end - start) / 1000 / 60) + " minutes");
    }

    private static Graph<Integer, DefaultWeightedEdge> readGraph() throws IOException {
        Graph<Integer, DefaultWeightedEdge> result = new DefaultUndirectedWeightedGraph<>(DefaultWeightedEdge.class);

        BufferedReader br = new BufferedReader(new FileReader("/home/semen/tmp/output.csv"));
        br.readLine();
        String line;
        while ((line = br.readLine()) != null) {
            String[] parts = line.split(",");
            Integer source = Integer.valueOf(parts[1]);
            Integer target = Integer.valueOf(parts[2]);
            double weigh = Double.parseDouble(parts[3]);
            Graphs.addEdgeWithVertices(result, source, target, weigh);
        }
        return result;
    }
}
```

Please let me know if this helped understand the issue.

Best,
Semen Chudakov

**Comment by mbasa** [comment]
Thanks. So this will be better suited for sparse graphs then?

**Comment by SChudakov** [comment]
Yes, correct. This algorithms was designed specifically for road networks, since they have low average out degree. For other types of graphs this algorithm will create a very large memory footprint, which is why using it becomes inefficient.

**Comment by mbasa** [comment]
Thanks. Curious though, you used a value of `10` for the ThreadPool. Is this the most optimal?

**Comment by SChudakov** [comment]
Sorry for the late response. No this values was chosen arbitrarily for testing purposes. In fact there is no static optimal number of threads for this algorithm, because it depends on the state of our system. If you do not have any other heavy processes running, like for example Chrome, then I would suggest to choose the number of logical cores on your machine.
Otherwise there is no precise way to measure the number of threads to choose for computations for this algorithm.

**Comment by mbasa** [comment]
Thanks @SChudakov
