### ISSUE TITLE
Finite State Machine (FSM, Automata) using JGraphT

### ISSUE THREAD

**Issue by drfred1981** [jgrapht/jgrapht#130]
Hello
Is there an implementation using JGraphT of FSM, with determinization, minimisation, language detection, etc. ?
Thanks for all
F.

**Comment by jkinable** [comment]
Currently, afaik, there is no notion of FSM in jgrapht; it's a pure graph library. FSM is more of an 'application'. Nevertheless, it's easy to represent an FSM in jgrapht by defining nodes and state transitions through directed edges.

**Comment by roniko1994** [comment]
Hello jkinable!
Can you please tell me how you would create two edges pointing from one node to another without having to draw one edge on top of the other?

Thanks!

**Comment by jkinable** [comment]
JgraphT is an algorithm's library. It is not meant to draw anything. If you want to draw graphs, use JgraphG instead. The latter library comes with algorithms for automated graph visualization, to prevent overlapping nodes/edges etc. You can also use both JgraphT and JgraphG together. JGraphT has an adapter class which allows you to transform your JGraphT graph into a JgraphG graph. This is nice if you want to combine the algorithmic capabilities of JgraphT with the visualization of JgraphG. Best to check the manual/javadoc of both JGraphT and JgraphG on how to do this. If you are purely interested in drawing, you are better off using JgraphG directly.

**Comment by roniko1994** [comment]
Did you mean JGraphX instead of JGraphG? I couldn't find anything about JGraphG.

**Comment by jkinable** [comment]
Yes, I meant JGraphX. Sorry for that.

Joris

**Comment by jkinable** [comment]
I would do the following:
1. Code your BDD in JgraphT
2. Convert the resulting graph into JGraphX using the adapter class in
Jgrapht.
3. JGraphX has several classes for automated graph Visualization. It pretty
much decides by itself where to put the vertices on the screen. BDD's are
highly structured. In fact, a normal BDD is a DAG (Directed Acyclic Graph)
which makes it much easier to visualize. I'm by no means an expert on Graph
Visualization, but have a look at this topic, and in particular
mxParallelEdgeLayout in combination with the mxHierarchicalLayout:
http://stackoverflow.com/questions/5603306/jgraphx-auto-organise-of-cells-and-bidirectional-edges

If you want to go really fancy, you can create a Listenable graph in
JgraphT and make JGraphX listen to changes in the the JgraphT graph. As
such, if you start with an unreduced BDD and reduce it, you get to see the
changes updated on your screen :).

Btw, I'm curious, with whom/where are you working on BDD's?

br,

Joris

**Comment by roniko1994** [comment]
Thanks for the quick response!

I am a final year student in CS and BDDs is the topic I am writing my thesis on. Therefore, I have to create an educational tool which lets users get familiar with BDDs and their reduction steps. First of all, the users should enter a truth table which is then used to create a BDD. Following that, there are 3 reduction steps that can be applied. So far, I have a Listenable MultiGraph representing the corresponding BDD and I've implemented all reduction steps. 

One problem that may arise is that when I create a BDD in JGraphT and then translate it to JGraphX, I wouldn't be able to apply any of the reduction steps that i've already coded for a JGraphT graph. This is something you have mentioned in your previous post. Does this mean that when I apply a reduction step to a Listenable graph in JGraphT it is automatically going to reflect the changes in the JGraphX graph displayed on the screen?

**Comment by jkinable** [comment]
>
> One problem that may arise is that when I create a BDD in JGraphT and then
> translate it to JGraphX, I wouldn't be able to apply any of the reduction
> steps that i've already coded for a JGraphT graph. This is something you
> have mentioned in your previous post. Does this mean that when I apply a
> reduction step to a Listenable graph in JGraphT it is automatically going
> to reflect the changes in the JGraphX graph displayed on the screen?
>
You should only implement your reduction algorithms in JgraphT. JGraphX is
merely a visualization of the graph maintained in JgraphT. There are 2
things you could do:
1. Write code in JgraphX which displays the JGraphT graph through the
adapter class. Each time change your JgraphT graph, you can reinvoke the
JGraphX display class. E.g.

graph=buildJgraphTGraph();
printJgraphXGraph(graph);
updateJgraphTGraph(graph);
printJgraphXGraph(graph);

2. A cleaner solution would be to use an Observer Design pattern, for
example through a listenable graph in JgraphT. Each time you change the
jgraphT graph, e.g.. add/remove edge/vertex, its observers are informed
about these changes. So if you write a JgraphX class which observes the
JgraphT model, it should be able to visualize your changes.
See this example: http://jgrapht.org/visualizations.html

br,

Joris

**Comment by roniko1994** [comment]
Hello Joris!

Thanks for your help. I have done some amazing stuff in the last 2 weeks. 

I need your help/advise again though. I want to be able to save/load a graph. I found the GraphMLExporter class which lets me save a graph to a file. However, how can I recreate a graph from a file after that? Preferably, I would like to associate each graph with its boolean formula. e.g. p->q : OBDD

Furthermore, I would like to implement some of the algorithms that can be applied to OBDDs - apply, restrict and exists. First, I would implement algorithm apply as it seems to be the most complicated out of all 3. In order to use algorithm apply, I must have 2 OBDDs. What I think I should do is to have a single OBDD in one instance of my application. Therefore, I would end up with two independent instances of my application with 1 OBDD displayed in each instance. However, I would need a way to temporary save an OBDD, to a file/database, shown in each application window, so I can make a connection between the two instances of the application. This is what I just came up with. I don't think that it is the right way of doing it and I hope that it makes sense to you. Any advice would be appreciated.

Thanks!

**Comment by jkinable** [comment]
Hi,

I'm not very experienced with exporting graphs since I rarely do this. As
far as I know, there are 4 ways to export a graph:
-as a GraphML
-as a DOT file
-as a CSV file (I think there's one export class included, and there is
experimental export/import class for CSV's in one of the open pull requests
on jgrapht's github)
-as a matrix

I have absolutely no idea whether JgraphT also provides import classes for
these formats. I presume so, otherwise it would be a great idea to include
them.

I'm not familiar with the apply/restrict/exist algorithms on an OBDD. I'm
not sure what you want to achieve or why you want to maintain 2 separated
instances? In general, exporting/importing graphs through IO procedures is
slow; I would avoid this. Why not make a copy in memory? JgraphT's classes
are serializable so you should be able to create a deep copy
straightforwardly. Then again, I'm not sure I understand why you want to
copy your graph to a file so this may not be very useful advise.

Joris

**Comment by roniko1994** [comment]
Hi Joris!

Thanks for the quick response!

I would like to have a separate instance of my app for each OBDD. The reason for this is that if I draw 2 non-reduced diagrams on the screen, it becomes kind of messy and then if I want to apply an algorithm to the two diagrams, a new diagram should be displayed. Therefore, I would end up with 3 diagrams in the same application window.

I tried saving a ListenableGraph to a database by converting the graph to an object and then storing it in the database as a 'blob' type. However, I got an exception that JGraphModelAdapter is not serialisable. I couldn't find any examples on how to make a deep copy of a graph. The reason for saving a graph is that when I have multiple instances of the application, I would like to temporarily save each OBDD shown in every instance of the app, so I can somehow make a connection between both OBDDs.

**Comment by jkinable** [comment]
I'm still not sure why you want to store a physical copy of the graph on
disk, or why that would things "less messy". I assume that you are not
drawing graphs on top of each other, but in separate windows or multiple,
non-overlapping panes. Either way, there are multiple ways to copy a graph
in memory:
-1. shallow copy: use addGraph on an empty graph instance:
http://jgrapht.org/javadoc/org/jgrapht/Graphs.html#addGraph(org.jgrapht.Graph
-2. shallow copy using clone() in AbstractBaseGraph:
http://jgrapht.org/javadoc/index.html?org/jgrapht/Graphs.html
-3. Use Serialization for a deep copy.
-4. Implement your own deep copy function.

Make sure you use the latest version of JgraphT. The error you get seems
suspicious as JGraphModelAdapter *does* implement serialisable; you may
want to troubleshoot this.

**Comment by roniko1994** [comment]
Hi Joris!

The error I am getting is java.io.NotSerializableException: org.jgrapht.ext.JGraphXAdapter. I am not saving the actual adapter but instead I am saving a DefaultListenableGraph instance.

**Comment by roniko1994** [comment]
Hi Joris!

Is there an implemented algorithm which finds all paths(not shortest paths) between 2 nodes in a directed graph?

Thanks!
