### ISSUE TITLE
Bridges and Cut vertices in Directed Graphs

### ISSUE THREAD

**Issue by keshete** [jgrapht/jgrapht#172]
Hi,
Are there algorithms for finding bridges and cut vertices (articulation points) in directed graph?
The only relevant thing I could find was getCutpoints() in BiconnectivityInspector, but this is for undirected graphs (+it's not all I need).
Thanks!

**Comment by thirtyfootsmurf** [comment]
This might help: http://jgrapht-users.107614.n3.nabble.com/minimum-cut-in-a-directed-graph-td4024852.html

**Comment by jkinable** [comment]
An articulation point in a graph is a vertex which, when removed together with all edges incident to it, increases the number of connected components in a graph. Whether the graph is directed or undirected is (as far as I know) irrelevant in this definition. You could simply do the following:
1. Convert your directed graph to an undirected graph, using the `AsUndirectedGraph` wrapper.
2. Use the BiconnectivityInspector on the resulting graph.

Currently we don't have a way to compute bridges. This however should be really easy to add, since computing articulation points is very similar to computing bridges. This would only require some minor modifications to the `dfsVisit` method in `BlockCutpointGraph`.

**Comment by jkinable** [comment]
Pull request #424 addresses this enhancement. The BiconnectivityInspector can now iterate over a variety of graphs (including directed and disconnected graphs). Moreover, the BiconnectivityInspector computes both bridges and cut vertices.
