### ISSUE TITLE
BronKerboschCliqueFinder

### ISSUE THREAD

**Issue by srikanthBezawada** [jgrapht/jgrapht#202]
Hi ,
I have a network and I need to extract all the cliques of size=3 in my network. They need not be *maximal cliques*.

I see BronKerboschCliqueFinder supports only maximal cliques. **Is there anyway to retreive all cliques of size=3  in my network ?**

**Comment by jkinable** [comment]
I haven't looked at the BronKerboschCliqueFinder but finding cliques of size=3 is relatively easy. 
Simply iterate over all edges (i,j). For each neighbor k of i, such that k != j, check whether the graph contains edge (k,j). If so, you found a new clique {i,j,k}.
Runtime would be O(E*V). However, since you only iterate over the neighbors of j, the average runtime will be significantly lower (assuming that you are not computing this for a complete graph).

**Comment by srikanthBezawada** [comment]
Thanks @jkinable , I've used the same approach and got it working. One thing to take care of in the above approach is to avoid duplicate cliques.
