### ISSUE TITLE
KDisjointShortestPaths

### ISSUE THREAD

**Issue by assimiz** [jgrapht/jgrapht#235]
Following my last [contribution to KShortestPaths](https://github.com/jgrapht/jgrapht/pull/228) I thought of utilize it to provide a way to find K disjoint paths on a graph. I am asking because I feel this problem is somewhere on the border between being applicative to pure theoretical problem. Also, I am planning to implement it using a `PathValidator ` which collects the already used edges and blocks any request to reuse them. So, it is kind of a greedy approach, not optimizing the overall length of the complete set of paths.

What do you think?

**Comment by jkinable** [comment]
No I don't think this is a good idea. This would be more of a demo of your PathValidator. There exist however much more efficient algorithms dedicated to the problem of finding k-disjoint shortest paths.
If you are interested, have  a look at the book: Bhandari, Ramesh (1999). Survivable networks: algorithms for diverse routing 477. Springer. p. 46. ISBN 0-7923-8381-8.

Btw, this is not a theoretical problem; it's actually used quite often. Think about building a reliable, survivable glass fiber network. I one cable is cut (happens often due to for example excavation/construction), then you don't want your network to fall apart. So you need an alternative, disjoint path.

**Comment by assimiz** [comment]
Thanks for the enlightening explanation.
I am aware of the more efficient methods for K disjoint paths such of Suurballe and Bhandari. Thought of implementing these too. However, I think there should be place for more than single approach, all the more when each comes with its cons. and pros. Suurballe/Bhandari algorithms require the modification of the graph (edge weights) as well as, for example, the naive approach of running K iterations of Dijkstra while removing the used edges from the graph between iteration. However, the main purpose of using `PathValidator was to avoid the modification/copy of the graph for cases when it is shared/big, respectively. So, there is place for both I think.
