### ISSUE TITLE
VertexCoverTest runs for a long time

### ISSUE THREAD

**Issue by jsichi** [jgrapht/jgrapht#244]
@jkinable @nolberg I just pulled the latest codebase and ran mvn test, and VertexCoverTest chugged away for a long time without ever finishing (probably due to memory or something?)  On Travis, it completed, but it took 50 seconds:

https://travis-ci.org/jgrapht/jgrapht/builds/149749736

The unit tests which run by default should not take more than a few seconds each.

If you look in jgrapht-core/pom.xml, we already had one case where we had to exclude some long-running tests:

<exclude>**/perf/**</exclude>

Please do something similar for tests which need to run something thorough, and then add a code coverage test with a tiny case which runs quickly by default.

**Comment by nolberg** [comment]
Yes, I noticed that, too. The testFind2ApproximationCover() method seems to be the issue. I ran all other tests without testFind2ApproximationCover(), and it finished after a total of 3 seconds. I have no idea so far why this is the case since I did not make any changes to the 2-approximation implementation and also did not write the test.

**Comment by jkinable** [comment]
Will fix it tonight. Problem is in the testFind2ApproximationCover which
checks whether the approximations are actually 2 approximations by solving
the vertex cover problem to optimality on reasonably large graphs

**Comment by jkinable** [comment]
Alright, should be fixed in pull request #246

**Comment by jsichi** [comment]
I've merged it, thanks!
