### ISSUE TITLE
does jgrapht works with android studio?

### ISSUE THREAD

**Issue by IbnB** [jgrapht/jgrapht#312]
hello All,
I am trying to use jgrpht library in my android project but I'm getting the  unsupported class file error below. Please, is jgrapht library supported on android, if yes what may be the cause of this error , otherwise could you suggest any graph theory library that works on android?
> Error:PARSE ERROR:
unsupported class file version 52.0
...while parsing org/jgrapht/DirectedGraph.class
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

**Comment by jkinable** [comment]
Did you try this :
http://stackoverflow.com/questions/37902840/got-unsupported-class-file-version-52-0-after-including-a-module-to-a-project

It seems to be a common error related to compatibility issues. Jgrapht
1.0.0 requires Java 1.8.

On Oct 4, 2016 8:59 AM, "IbnB" <notifications@github.com> wrote:

hello All,
I am trying to use jgrpht library in my androdi project but I'm getting the
unsupported class file error below. Please, is jgrapht library supported on
android, if yes what may be the cause of this error , otherwise could you
suggest any graph theory library that works on android?

Error:PARSE ERROR:
unsupported class file version 52.0
...while parsing org/jgrapht/DirectedGraph.class
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
com.android.build.api.transform.TransformException:
java.lang.RuntimeException: java.lang.RuntimeException:
com.android.ide.common.process.ProcessException:
java.util.concurrent.ExecutionException:
java.lang.UnsupportedOperationException

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jgrapht/jgrapht/issues/312>, or mute the thread

**Comment by jkinable** [comment]
This may be relevant as well :
http://stackoverflow.com/questions/23318109/is-it-possible-to-use-java-8-for-android-development

See first answer. It seems as of 2016,android does not yet fully support
Java 8. Java 7 now seems to be fully supported. You could try an older
version of jgrapht, anything prior to version 1.0.0 and see whether that
works.

On Oct 4, 2016 9:43 AM, "J Kinable" <j.kinable@gmail.com> wrote:

Did you try this : http://stackoverflow.com/questions/37902840/got-
unsupported-class-file-version-52-0-after-including-a-module-to-a-project

It seems to be a common error related to compatibility issues. Jgrapht
1.0.0 requires Java 1.8.

On Oct 4, 2016 8:59 AM, "IbnB" <notifications@github.com> wrote:

hello All,
I am trying to use jgrpht library in my androdi project but I'm getting the
unsupported class file error below. Please, is jgrapht library supported on
android, if yes what may be the cause of this error , otherwise could you
suggest any graph theory library that works on android?

Error:PARSE ERROR:
unsupported class file version 52.0
...while parsing org/jgrapht/DirectedGraph.class
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
com.android.build.api.transform.TransformException:
java.lang.RuntimeException: java.lang.RuntimeException:
com.android.ide.common.process.ProcessException:
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperation
Exception

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jgrapht/jgrapht/issues/312>, or mute the thread

**Comment by IbnB** [comment]
@jkinable , After downgrading the jgrapht version from 1.0.0 to 0.9.0 , no more error , it works succesfully. Many thanks for your recommendation, much appreciated.
Cheers,
