### ISSUE TITLE
getEulerianCircuitVertices in EulerianCircuit needs a rework

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#313]
Issues with `EulerianCircuit.getEulerianCircuitVertices(...)`:

1. The function should return a `GraphWalk`, instead of a `List`
2. If possible, the function should operate on a Graph, instead being limited to UndirectedGraphs
3. If possible, the description should mention which the name of the algorithm used to produced the result. There exist multiple algorithms to solve this problem, some of them are inefficient.

**Comment by d-michail** [comment]
I had a look at this one today. The current implementation seems to be a variant of HielHolzer's algorithm which if implemented properly is linear. However, the current implementation is not linear.

A simple solution would be to reimplement it using the Subgraph class (either directed or undirected), but this would still not be linear due to our current subgraph implementation (issue #296). Another possible solution is to create a restricted subgraph which will be indexing the edges but only allowing edge and vertex removals. This helper could also be used in the `EdgeBasedTwoApproxVCImpl`.

I will try to have a first suggestion using the current subgraph.

**Comment by d-michail** [comment]
Done in pull request #314.
