### ISSUE TITLE
How to import a ready made JgraphT so that I can use it in a different program. 

### ISSUE THREAD

**Issue by HelenMamalaki** [jgrapht/jgrapht#32]
I am asking this question because my program takes half an hour to create a graph of 16000 nodes (3x 16000 to get edge no). I don't know why it takes so long. I use my own Vertex and Edge class. So I figured perhaps I can precompute the graph (for half an hour!) and then import a ready populated version for visualizationa and further processing.

**Comment by the21st** [comment]
I am having a similar issue - constructing a large graph (50k nodes, 200k edges) takes a very long time, because of checking whether the edge that is being added already exists, even though I know it doesn't.

**Comment by jkinable** [comment]
Many improvements to the library have been made since this issue was opened. Many of the graph importers have become much more efficient. Similarly, efficiency improvements have been made to the underlying graph structures. Let us know if you encounter more issues. If the issue persists, please post a small working example.
