### ISSUE TITLE
calculating costs depending on the verticies travelled

### ISSUE THREAD

**Issue by liechtir** [jgrapht/jgrapht#333]
check my brief description on [stackoverflow](http://stackoverflow.com/questions/40790622/creating-a-cost-function-in-jgrapht).
I miss the possibility to define an additional cost to be evaluated using the Djikstra depending on the path chosen. A path with more hops but less actions might be cheaper to travel then a path with less hops but more actions necessary (like rotating a car).

**Comment by jkinable** [comment]
Answered on stackoverflow, can be closed here.

**Comment by liechtir** [comment]
Hi Joris, I think this should not be closed but native support for cliques would be a good thing to have in jgrapht. So to speak support for grouping nodes based on some criterias.

**Comment by jkinable** [comment]
The issue stated in this issue is simply too vague to follow up and not self-contained. It's mixture of a question and something that may or may not be missing. The question you posted on stackoverflow can be solved in various ways depending on the application. There's not a straightforward way to capture this in a single generic algorithm.

a. if you feel that jgrapht is missing functionality, feel free to open up a new concise Enhancement request (new issue labeled 'enhancement'). Clearly outline what is missing, and why it is necessary/beneficial. Potentially support with an example. Obviously, the enhancement must be generic enough that multiple people can benefit from such the enhancement (i.e. nothing application specific).

b. Enhancement requests are usually ignored unless another person needs that feature... so your best bet to get your enhancement in the library is to implement it yourself and submit a pull request :)

When you submit your request, be careful in your word choice: for instance, "clique" has a very specific meaning in the context of graph theory. Furthermore, I wouldn't know what you mean by "grouping nodes" and what you want to achieve with that.
