### ISSUE TITLE
Unexpected version of DefaultEdge

### ISSUE THREAD

**Issue by jaabio** [jgrapht/jgrapht#342]
I just wanted to say: I'm new to JGrapht and wanted to see if I could use it to generate random graphs and how.  Unfortunately for me, I spent the last 3 hours trying to figure out why the edges generated didn't seem to have any vertices.  Finally, lo and behold, I realized I was using the jgraph version of DefaultEdge, not the jgrapht one.   :(...

**Comment by jkinable** [comment]
For an introductory example, check out the wiki: https://github.com/jgrapht/jgrapht/wiki/HelloWorld
For tons and tons of code examples, check out the test classes in the source code. Every class has an accompanying test class, so you get a lot of examples you can just copy.
Btw, jgrapht doesn't care about the type of object you use as an edge, so you can certainly make random graphs using jgraph.DefaulEdge as the edge type. Have a look at some of the random graph generators. See http://jgrapht.org/javadoc/org/jgrapht/generate/package-frame.html for details.

I'm closing this issue since it's not a question/enhancement/anything actionable.
