### ISSUE TITLE
maven-assembly-plugin issue

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#351]
As of version 2.2, the maven-assembly-plugin (which is used in jgrapht-dist/pom.xml), requires that an ID descriptor is provided. See https://maven.apache.org/plugins/maven-assembly-plugin/faq.html#required-classifiers for details.

Whenever an ID is not provided, the following error is thrown:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4.1:single (default) on project jgrapht-dist: Assembly is incorrectly configured: null: Assembly is incorrectly configured: null:
[ERROR] Assembly: null is not configured correctly: Assembly ID must be present and non-empty.

To get rid of the error, I've made the following changes:
1. jgrapht-dist/pom.xml (under maven-assembly-plugin):

- added `<id>assembly</id>`
- added `<appendAssemblyId>false</appendAssemblyId>`

2. jgrapht-dist/src/assembly/assembly.xml

- added `<id>assembly</id>`

I'm not entirely sure whether this configuration is correct, and/or what ID I was supposed to specify. Please verify.

@d-michail do you have any experience with this?

**Comment by d-michail** [comment]
I think this setup is fine in our case. The crucial part was to disable appending the assembly id, otherwise it would mess up with the package name.

[https://maven.apache.org/plugins/maven-assembly-plugin/faq.html#required-classifiers](https://maven.apache.org/plugins/maven-assembly-plugin/faq.html#required-classifiers)
