### ISSUE TITLE
Missing GmlParser class

### ISSUE THREAD

**Issue by Elsee** [jgrapht/jgrapht#353]
I'm trying to build your project and this error appears: http://joxi.ru/5mdXz7fkeVL6m1. Class GmlParser is not found.

**Comment by jkinable** [comment]
Can you be more precise as to what exactly it is you are doing? Which
commands did you use to build the project?
-Did you download the precompiled jars?
-are you using maven?
-did you download the sources from our github repository and are you trying
to compile those with maven?
-which version of jgrapht are you using?

**Comment by Elsee** [comment]
I downloaded version 1.0.1 from github repository, opened it with InteliJ IDEA, compiled with maven.

**Comment by jkinable** [comment]
@d-michail Could you look into this? I was able to reproduce this issue. To reproduce, do the following steps:
1. Download source from git:
git clone https://github.com/jgrapht/jgrapht.git .
2. Open a new project in intellij by importing the project: https://www.jetbrains.com/help/idea/2016.3/importing-project-from-maven-model.html

To temporary resolve the issue, I did the following:
1. in the directory with the source files, run the command: mvn test
This will compile all the code using maven. For some reason, this works fine.
2. In intellij under project structure, right click the 'org' folder under jgrapht-ext>target>generated-sources>antlr4. Select Mark directory as -> sources root.

Summary of the problem: intellij doesn't seem to generate those antlr sources. After generating them, they still have to be included manually by marking the directory as 'sources'.

**Comment by jkinable** [comment]
To follow up, it seems to be an intellij specific issue. See for instance: [](http://stackoverflow.com/questions/25902126/intellij-will-not-recognize-antlr-generated-source-code)
Not sure whether we can fix this.

**Comment by d-michail** [comment]
Indeed, this is an IntelliJ issue which seems to be bothering a lot of people. Our setup is following all standard conventions, which means that we cannot really fix anything.

As @jkinable pointed out the problem seems to be that IntelliJ is not adding the folder `jgrapht-ext/target/generated-sources/antlr4` as a `sources` folder. Doing this manually resolves the issue.

Another option that works (in IntelliJ 2016.3) is to import and then right click on the project `jgrapht-ext` and run `Maven->Generate Sources and Update Folders".

**Comment by d-michail** [comment]
Updated the [Contributor-Guidelines wiki page](https://github.com/jgrapht/jgrapht/wiki/Contributor-Guidelines) with instructions for the major IDEs.

Thanks for reporting!
