### ISSUE TITLE
Efficiency of FloydWarshallShortestPaths::lazyCalculateMatrix()

### ISSUE THREAD

**Issue by huanfachen** [jgrapht/jgrapht#406]
Hi all. I am working with a undirected graph with 5980 nodes and 11632 edges. I want to calculate the diameter of this graph, using the FloydWarshallShortestPaths::getDiameter() function in Java. It took about 653 seconds to finish. Looking into the code, it seems that lazyCalculateMatrix() is the bottleneck of getDiameter(). Is there any way to speed up getDiameter(), or any other class with more efficient solutions? Thank you for any suggestion! 
I am using Java 1.8.0_66 and jgrapht-core 0.9.2 in Eclipse. The environment is Windows 7, with 2 3.6GHz Intel i7 cores and 32 GB RAM.

**Comment by jkinable** [comment]
I would start by upgrading your jgrapht. The version you are using is
outdated. Quite a few improvements were made to jgrapht in later versions.

The graph diameter is defined as the longest shortest path. So a trivial
way to get the diameter is to compute an all pair shortest path like
FloydWarshall does, and then return the longest distance between any pair
of vertices.
The lazyCalculateMatrix() in FloydWarshall populates the distance matrix
containing all shortest path distances. This method is the core of
FloydWarshall's algorithm. There's no way you can avoid this, because you
need that distance matrix...
The runtime complexity of FloydWarshall to calculate the distance matrix is
n^3, where n is the number of nodes. In your case, that translates to:
5980^3=213,847,192,000, which is quite a lot... Once the distance matrix is
calculated, you still need to iterate over all pairs to find the longest
distance, resulting in another n^2=35760400 computations.

Since your graph is relatively sparse, I would recommend using the Johnson
shortest path algorithm instead of FloydWarshall. Johnson's algorithm was
added to jgrapht in 2017, so you would definitely have to upgrade to a
newer version of jgrapht. Johnson's  algorithm computes an allpair shortest
path in O(n^2*log n+n*m), where m is the number of edges. In your case,
that would translate to 518,206,826 computations. That's still a lot, but
significantly less than FloydWarshall, and may be fast enough for your
application. The current implementation of Johnson's algorithm doesn't come
with a getDiameter function, but you can easily implement this yourself:

Method getDiameter():
ShortestPathAlgorithm<V,E> johnson=new JohnsonShortestPaths<>(graph);
double diameter=0;
for(V u : graph.vertexSet)
 for(V v : graph.vertexSet)
  diameter=Math.max(diameter, johnson.getPathWeight(u,v);
return diameter;

There may exist faster dedicated algorithms to compute (or estimate) the
diameter of a graph, but that may require some research. A good starting
point would be this topic:
https://cs.stackexchange.com/questions/194/the-time-complexity-of-finding-the-diameter-of-a-graph
Also, in case your graph has some special structure, e.g. chordal, or
bipartite, .... , you may find a dedicated algorithm which takes advantage
of the graph's special structure.

Hope this helps.

**Comment by jkinable** [comment]
Forgot to mention: Johnson's algorithm is not yet included in any release of jgrapht (it will be part of the next release). The code is however in the master branch (fully tested and functional). So you'll have to pull the master branch and build a jar yourself. to do so, download the master repository to your computer, and then run `mvn package`.

**Comment by huanfachen** [comment]
Thanks @jkinable . Your reply is really helpful. 
I tried to use jgrapht-core-1.0.1, but the computational time is almost the same.
Then, I built the jar jgrapht-core-1.0.2-SNAPSHOT, and used JohnsonShortestPaths to calculate the diameter. It is 10 times faster than FloydWarshallShortestPaths, although the cost is 100% CPU usage. Moreover, JohnsonShortestPaths has a _path_ attribute, which stores the path between any pair of nodes, which can be used repeatedly and efficiently. 
One more question, would it be much more efficient to use igrapht in C++ than in Java? (I never use igrapht in C++)

**Comment by jkinable** [comment]
@huanfachen I have no idea whether igraph would be faster. It will largely depend on the efficiency of their implementation. If you do end up trying, I would be very interested to hear about your results. One fast way to find out is to:

1. Export your current graph in jgrapht using one of our many exporters.
2. Importing the graph in igraph [doc](http://igraph.org/c/doc/igraph-Foreign.html)
3. Running igraphs method to compute the diameter and measuring the time it takes to complete this method (exclude the time it takes to import the graph).

Although we try to implement our algorithms as efficiently as possible, we do occasionally make some trade-offs wrt code re-usability, genericity (being able to easily swap algorithms or graph types) and user-friendliness (e.g. spending computation time on checking data, and returning an informative error message if the data is incorrect, instead of allowing an algorithm to crash).

I'm not so sure what you mean by: 

> It is 10 times faster than FloydWarshallShortestPaths, although the cost is 100% CPU usage. 

When you use FloydWarshallShortestPaths, your CPU usage should also be 100%. In fact, on you graph, FloydWarshall does need at least 200 times as many computations as JohnsonShortestPaths.

Also, what do you mean by: 

> Moreover, JohnsonShortestPaths has a path attribute, which stores the path between any pair of nodes, which can be used repeatedly and efficiently.

FloydWarshall has the same interface as JohnsonShortestPaths, so it has the exact same functionality.

**Comment by d-michail** [comment]
Also note that in order for any comparison to be fair, you have to make sure that you trigger the C2 compiler of the JVM (assuming you are using a hotspot JVM) in order to replace "hot" methods with the most efficient native implementations. 

This means that you first need to warm up the code (by running a few times without measuring) and then measure.

**Comment by huanfachen** [comment]
@jkinable Thanks for your suggestion!

> I have no idea whether igraph would be faster. It will largely depend on the efficiency of their implementation

I have used igraph in R to determine the diamter of this graph. The computational time is 5 seconds, comparing with 60 seconds using JohnsonShortestPaths of jgrapht in Java. However, this does not represent the performance of igraph in C or python, as the implementation may be different.
Although igraph is more efficient in determining graph diameter, it is not suitable for my project, as my project is pure Java and largely based on jgrapht, and igraph does not have mature Java implementation.

> One more question, would it be much more efficient to use igrapht in C++ than in Java? (I never use igrapht in C++)

Sorry for the typo. I wanted to say jgraph in C++ instead of igrapht. My question is, is jgrapht in C++ much faster than jgrapht in Java?

> FloydWarshall has the same interface as JohnsonShortestPaths, so it has the exact same functionality.

Sorry that I did not look into details of FloydWarshall. I would like to thoroughly compare FloydWarshall and JohnsonShortestPaths on the graph that I am working with, regarding time, CPU, etc. @d-michail Also thanks for your suggestion on the fair comparison. 
I am not familiar with the performance comparison in Java. Do you have any suggestion on the tools for this comparison? Thanks!

**Comment by jkinable** [comment]
You can now compute the graph diameter using the `GraphMetrics` class, or if you need more control, through the `GraphMeasurer` class.
