### ISSUE TITLE
Seeking ways to efficiently compute the center of a subgraph

### ISSUE THREAD

**Issue by huanfachen** [jgrapht/jgrapht#419]
Hi all. I am working on a problem that frequently needs to compute the center of a subgraph of a given graph. The whole graph does not change, while the considered subgraph often changes. The definition of the graph center is the Jordan center (https://en.wikipedia.org/wiki/Graph_center).

I am using jgrapht in Java. To efficiently compute the center of a subgraph, I store the distance matrix in a double[][] objects, and use a two-layer loop to query the center node. However, this is still not sufficiently efficient. 

Is there any existing algorithm or data structure to speed up the computation of getCenter() on a subgraph?

Possible techniques include using a cache to store the center of subgraphs that have been considered. But I am not sure how much speedup it may provide. Will test it later.

Thanks for any suggestions!

**Comment by jkinable** [comment]
Recently the GraphMeasurer class was added to the jgrapht master
repository. This class includes a method to compute the graph center. This
you could use as a baseline. Obviously, this method is not optimized for
recomputing the graph center for subgraphs of the original graph.

In order to compute the graph center, you need a pairwise distance map.
Computing this distance map is usually pretty expensive (n^3) for
FloydWarshall, slightly better if you use Johnsons algorithm (the latter
algorithm is also in the master repository). Each time you take a subgraph
of the original graph, your distance matrix may change. Assume for instance
that the shortest path from a vertex u to a vertex v is [u,w,v]. If your
subgraph does not contain vertex w, then this path is no longer valid and
you have to recompute the shortest path for u to v.
So the first question you'll need to answer is: does the distance matrix
change if the subgraph changes, and if so, can maybe you could
incrementally repair your distance matrix without having to recompute it
entirely.


The eccentricity e(v) of a vertex v = max_{x\in V} d(v,x), where d(v,x) is
the shortest path from v to x.
The radius r of a graph is: min_{v \in V} e(v).
The center of a graph is {v\in V : e(v)=r}, i.e. all vertices with
eccentricity equal to the radius of the graph.

Let's say that your original graph is G, and your subgraph is G'. All you
need to do is find out whether the radius of G' is still the same as the
radius of G. If this is the case, then the center of G' equals the center
of G minus the vertices which are in G but not in G'. However, if the
radius of G' is no longer equal to the radius of G, then you have to think
about whether there's an easy way to find out which vertices are are in the
new center.

Also, I don't know how large your graphs are, but there are various papers
discussing faster algorithms to compute for instance graph centers or graph
diameters. You may want to have a look at the techniques they use over
there. See for instance this topic:
https://cs.stackexchange.com/questions/194/the-time-complexity-of-finding-the-diameter-of-a-graph
(Graph diameter is closely related to computing the graph center). Also
this paper may be useful:
https://www.cs.cmu.edu/~ukang/papers/CentralitySDM2011.pdf

A final thought: if your graph has some special structure, e.g. distances
conform the triangle inequality, or the graph has a planar embedding, then
you may be able to use this structure to more efficiently update the graph
centers.


br,

Joris Kinable
