### ISSUE TITLE
Bug in AllDirectedPaths

### ISSUE THREAD

**Issue by bfreuden** [jgrapht/jgrapht#441]
As this is my first message here, let me first thank you for this great library!
I think I have found a bug in the org.jgrapht.alg.shortestpath.AllDirectedPaths class, in jgrapht 1.0.1.

Here is my test:

```
@Test
public void test() {
  DefaultDirectedGraph<String, String> graph = 
    new DefaultDirectedGraph<String, String>(String.class);
  graph.addVertex("A");
  graph.addVertex("B");
  graph.addEdge("B", "A");
  // so there is a single path in the graph: from B to A

  AllDirectedPaths<String, String> all = new AllDirectedPaths<>(graph);
  // failing below if run with the -ea JVM argument
  List<GraphPath<String, String>> allPaths = all.getAllPaths(
    graph.vertexSet(), 
    graph.vertexSet(), 
    true, 
    graph.edgeSet().size()); 
  System.out.println(allPaths); // will display: [[], [], []]
  // failing below if run without the -ea JVM argument
  assertEquals(1, allPaths.size()); 
}
```
An assert in AllDirectedPaths.java is detecting the error if JUnit test is run the -ea JVM option.

**Comment by d-michail** [comment]
Thanks for the bug report. 

A minor note: Do not use String class for the edges of the graph without explicitly providing an `EdgeFactory`. Otherwise the default behavior is to call `new String()` and then if you do `graph.addEdge("A","B")` or `graph.addEdge("B","C")` you create the same edge. 

We provide a class called `DefaultEdge` and `DefaultWeightedEdge` for such use cases. Your code would then look like the following, and indeed it seems that there is a bug.

```
DefaultDirectedGraph<String, DefaultEdge> graph =
    new DefaultDirectedGraph<>(DefaultEdge.class);
graph.addVertex("A");
graph.addVertex("B");
graph.addEdge("B", "A");
// so there is a single path in the graph: from B to A

AllDirectedPaths<String, DefaultEdge> all = new AllDirectedPaths<>(graph);
List<GraphPath<String, DefaultEdge>> allPaths = 
    all.getAllPaths(graph.vertexSet(), graph.vertexSet(), true, graph.edgeSet().size());
        
assertEquals(3, allPaths.size());
assertEquals("[[A], [B], [(B : A)]]", allPaths.toString());
```

This is related to #234. @agdphd Could you please take a look at this?

**Comment by bfreuden** [comment]
Thank you very much for taking time writing the note. My actual code is hopefully using a custom edge class, but that's very good to know.

**Comment by agdphd** [comment]
Sorry, I lost track of this last fall. To clarify, the issue here is that the algorithm is reporting [A] and [B] as paths, but you expect only [A, B]? If so, it's not clear to me that this is wrong, since you specified that each of A and B is both a source and a target; to get the desired output, just have your source set be [A] and your target set be [B]. I can certainly change it if needed for consistency with other shortest-path algorithms in JGraphT, though.

**Comment by d-michail** [comment]
From what I can recall the test above triggers an assertion. Just copy-paste into `AllDirectedPathsTest` and execute.

**Comment by agdphd** [comment]
Ah, got it--this is due to an edge case with maxPathLength==1. Sorry about the mess! PR inbound.

**Comment by d-michail** [comment]
Thanks!

Could you also add the above code as an additional test? Moreover, use checkstyle as
```
mvn checkstyle:check -Pcheckstyle
```
to check whether the code passes the build by Travis.

**Comment by agdphd** [comment]
Done and done.

**Comment by bfreuden** [comment]
Thank you very much for the fix!
