### ISSUE TITLE
FastLookupDirectedSpecifics does not use edgeSetFactory consistently, and blows memory

### ISSUE THREAD

**Issue by shevek** [jgrapht/jgrapht#459]
ArrayUnenforcedSetEdgeSetFactory contains an optimization forcing the default size of the ArrayUnenforcedSet to be 1, or 64 bytes.

https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/graph/specifics/FastLookupDirectedSpecifics.java#L131 does not use the factory or replicate the optimization, but creates a new ArrayUnenforcedSet with the default ArrayList size (10 in JDK8), which takes 136 bytes.

This more than doubles the memory usage of jgrapht on graphs with low edge cardinality, and is currently blowing out my RAM (I only have 144Gb).

The Undirected version presumably contains a similar bug, but I'm lazy and all my graphs are directed, so I haven't checked.

Numbers above are from visualvm's memory profiler, and me figuring out why I have so many nulls in memory.

**Comment by jkinable** [comment]
Good point, thanks for identifying this issue. I'll submit a patch.

Ps. It seems you are running large scale experiments. Out of curiosity, what do you use jgrapht for, and how does it scale (most of us do not have that amount of computation power at their disposal, so it's hard to evaluate). If you encounter other issues that affect performance, please let us know.

**Comment by jkinable** [comment]
btw, depending on the kind of queries you run, you might want to use DirectedSpecifics instead of FastlookupDirectedSpecifics. The former requires less memory, but several methods which rely on edge retrievals (e.g. getEdge(u,v), addEdge(u,v), containsEdge(u,v) etc) become slower.

**Comment by d-michail** [comment]
Indeed, if you do not require edge lookup queries you can override 

```protected Specifics<V, E> createSpecifics(boolean directed)```

in your graph and return a `DirectedSpecifics` instead of `FastLookupDirectedSpecifics`.

**Comment by shevek** [comment]
I'm actually using custom specifics now, because using a couple of instanceof calls to store single objects as an object pointer rather than a singleton ArrayUnenforcedSet reduces the memory usage by a further 20%. I only bother promoting to an ArrayUnenforcedSet once the size goes above 1. If you wanted to use that idea or code, you're welcome to, I'm sure it would benefit the world, but it's fractionally more complex than just calling ArrayUnenforcedSet(1). I'm wondering whether I can do even better by using fastutil's ObjectOpenCustomHashSet and building the object-array into the Pair, thus not having to have the Map.Entry at all, and saving a few more objects per node. JVM is about 40 bytes per object, which is a LOT.

I did try using DirectedSpecifics, but many of our (and your) algorithms rely on the fast lookups. We may be able to replace it with a DirectedNeighbourIndex. We're also currently storing most of the actual node/edge metadata off-heap; the only thing we need to keep in heap is the graph structure itself. We're starting to evaluate neo4j as an alternative to jgrapht; it may or may not be flexible enough.

Next on the hit list is that AbstractBaseGraph uses a LinkedHashMap for edgeMap, which is also very expensive, and appears to be hard or impossible to swap out without rewriting or replacing AbstractBaseGraph. The documentation suggests that an implementation is not required to maintain a linkage, but may do so. Again, we may experiment with ObjectOpenCustomHashSet and save 64 bytes per edge, but this would require a lot of rewriting of jgrapht.

At times, up to 50% of our JVM heap is (Linked)HashMap.Entry objects or the associated Object[] arrays for the tables, and that's a lot to pay. Of the top 10 heap users in our heap, nos 1, 3, 6, 8 and 9 are jgrapht. As for our use case: We are CompilerWorks, we write large scale compilers and optimizers. Making things smaller and faster is our business. :-)

**Comment by jsichi** [comment]
Regarding the edge map, didn't we make that customizable with the introduction of createIntrusiveEdgesSpecifics in AbstractBaseGraph?

Other JGraphT-based applications probably have hardcore requirements similar to yours, so it's worthwhile contributing optimizations (or at least adding any extension points necessary for shoehorning them in).

**Comment by shevek** [comment]
Probably, we're still on 1.0.1 - I looked at updating to 1.1.0 briefly yesterday to solve this, but hit a compile error, and I didn't have time to run a validation cycle. I may try again tomorrow, today is done for.

I would be VERY happy to contribute any information about optimizations; is the note above about further optimizing the specifics class enough, or should I post code? In general, the performance of jgrapht is sufficiently under our control that we can make it very good for our purposes. We mostly fight with memory size: Maps are really, really expensive.

**Comment by shevek** [comment]
So, the way it looks in 1.1.0, IF we use IntrusiveEdge as a base-class for the user edge, then the UniformIntrusiveEdgesSpecifics has a map with the IntrusiveEdge (i.e. vertex-pair) as the key, and so does the FastLookupDirectedSpecifics, which costs us TWO (Linked)HashMap.Entry objects and a Pair object per edge.

It looks hard to do an external general purpose implementation of IntrusiveEdgesSpecifics without edgeMap because it needs a custom user-defined class to make IntrusiveEdge.source and IntrusiveEdge.target accessible.

Actually, kill that, IntrusiveEdgesSpecifics isn't public, so I can't do that anyway. If I can hack this, it will reduce my memory usage by another 15%, so I would like to.

**Comment by shevek** [comment]
AAARGH... I can't generally override createIntrusiveEdgesSpecifics() because the interface is package-private. heh. I've put a few classes into the jgrapht package, and am experimenting more now....

(time passes)

So, results on a test dataset. My app memory usage is down by about 35%. Figures here are in megabytes of heap, from the profiler, in the format old -> new:

Decreases:
HashMap.Node: 370 ->127 (massive decrease)
ArrayUnenforcedSet: 269 -> 94 (wow)
LinkedHashMap.Entry: 465 -> 81 (wow)
jgrapht.Pair: 174 -> 0 (gone)
DirectedEdgeContainer: 71->71 (identical to the byte)

And increases:
Object[]: 574 -> 872 (increase)
CustomDirectedSpecifics.TouchingVertexEntry: 261 (replaces most of the above mechanisms)

What I did:
* Update to 1.1.0
* Custom DirectedSpecifics using fastutil's ObjectOpenHashSet, a custom bit-mixing strategy for the hash codes, and a single intrusive class to replace the whole Pair/HashMap.Node/ArrayUnenforcedSet.
* Custom IntrusiveEdgesSpecifics, trivial implementation, also using ObjectOpenHashSet.
* Custom subclass of DefaultDirectedGraph duck-punched into the jgrapht package, just to apply the custom IntrusiveEdgesSpecifics.

Conclusions:
Only 35% of my heap is now jgrapht structures; the rest is my business logic, and jgrapht only occupies 4 of the top 10 slots in the memory profiler, not 4 of THE top 4.

Other notes:
I note that addEdge() goes out to the edge specifics map twice: once via containsEdge() and once via add(). Since IntrusiveEdgesSpecifics is a new (currently private-ish) interface, it might be better to have add() return a boolean (per Set.add()) so that AbstractBaseGraph.addEdge() doesn't need to do a contains/get pair.

**Comment by d-michail** [comment]
My bad, interface `IntrusiveEdgesSpecifics` should be public.

**Comment by jsichi** [comment]
@shevek thanks for sharing the results.  Sounds like we need:

(1) making public IntrusiveEdgeSpecifics (including Base, Uniform and Weighted classes since people may want to adapt those as well), and changing the add() return type to boolean.

(2) maybe:  optimizing our default implementations.  I haven't taken a look at fastutil yet, but if it doesn't drag in a lot of additional dependencies, and it has other stuff we're likely to use later, then we can go with it.

Let's do these as two separate pull requests, starting with (1).

**Comment by d-michail** [comment]
I implemented (1). Thanks for the suggestions, this saves one `contains()` per edge insertion. 

Regarding (2), maybe we can allow the user to change the implementation of the maps using some factory delegation.

**Comment by shevek** [comment]
Pontificating now:

fastutil is pretty small and dependency-free, but not everybody wants it, and I do applaud dependency-free libraries in general[0]. I did wonder whether there was an opportunity for a "standard" small-fast optional module which provided the fastutil-based implementations. This would help the core team, as then the requirement to make the core jgrapht interfaces pluggable would be practical, rather than theoretical. One could use https://github.com/jbellis/jamm as a java agent to construct a test suite to show the reduction in memory usage.

I'd be happy to contribute much of what code we have to such a module, although I have limited time for doing general purpose public maintenance. However, I will always gladly return results from our applications, as we do have the time and resource to do the profiling, design and optimization to make this work.

Doing the trick where the edgeMap is completely redundant (because of the inherent capabilities of the directed specifics) would be harder, as it requires the detection of a particular (although common) situation. Right now, the optimization technically has an edge case because an IntrusiveEdge can be used in more than one Graph as long as the vertices are the same in each; the optimization would lose that ability.

[0] Ironically, one of the best AND worst dependencies in the business is Guava - it does everything you want, but it does it incompatibly with every other release of Guava. Sigh.

**Comment by jsichi** [comment]
(btw I've merged https://github.com/jgrapht/jgrapht/pull/462)

@jkinable @d-michail any opinions on the introduction of a new module for adding optimized implementations?  Perhaps this would make sense as a home for other specializations we've discussed as well (e.g. graphs where the vertex type can be mapped to unique integers).  Looks like fastjar could be nicknamed fatjar because they code-generate the implementation across a type matrix, so keeping the new module optional would make sense.

We might want to also consider a better pluggability mechanism, since overriding protected methods leaves a lot to be desired.  Instantiating a graph with a compound factory (instead of just an EdgeFactory) would be one way.

**Comment by d-michail** [comment]
Regarding the maps, we could delegate the map construction to a 'MapFactory' so that the user can change it. We have three points where maps are used, `Specifics`, `IntrusiveEdgesSpecifics` and the fast lookup optimisation. In the first two cases, a map with a consistent ordering is required. The latter case works with maps which do not have a consistent ordering. I will try to open a PR with this as soon as I find some spare time.

Regarding specialised graph implementations, I have one almost ready which uses a `Intrusive` approach. Users cannot change the graph edge or vertex, but it supports constant time operations instead of "expected" constant time (using linked lists). I will ask for comments on this implementation shortly.

Finally, it would make sense to introduce some specific graph which uses integers for graph vertices and use some space optimised representation, in a separate package.

**Comment by shevek** [comment]
The restriction of a MapFactory is that actually our tightest implementation(s) don't need some of the maps AT ALL. However you do a non-intrusive map, it's about 128 bytes minimum per key-value, which is a lot more than the data fields cost. If you're going to put up a module for optimized implementations, we can offer our highly optimized DirectedGraph specifics implementation.

**Comment by d-michail** [comment]
Yep, the maps are the "cost" that one has to pay for allowing the user to use any object as an edge or vertex.

@jkinable, @jsichi How would a "specialized" module for optimized implementations be called?

**Comment by jsichi** [comment]
Suggested naming:

artifactID = jgrapht-opt
package = org.jgrapht.opt

**Comment by d-michail** [comment]
One more related question whose answer will probably come up. Should there be any more "core" package separation. Currently the core package contains interfaces, our default graph implementation plus the algorithms.

It would make sense, to have the following packages
  - an api package (jgrapht-api)
  - a core graph implementation (jgrapht-core)
  - an additional specialized graphs package (jgrapht-opt)
  - a separate jgrapht-alg package with all the algorithms which would only depend on the api package

@jsichi, @jkinable Does this make sense?

**Comment by jsichi** [comment]
This will probably make sense at some point in the future.  I don't know that there's a compelling reason to make the split now.

(Note that some algorithms instantiate core graphs of their own internally as working copies or results, so breaking that dependency would require the introduction of factories.)

**Comment by jkinable** [comment]
Unless there's a good reason for the splitting, I would prefer not to create any additional packages. Currently the splits are already causing some problems. E.g. the NamedGraphGenerator is in jgrapht-core, but in order to include some larger Named graphs, ideally I would like them to store them in a compressed Graph6 format. Unfortunately, the importer for Graph6 is located in jgrapht-io, which would require a dependency on the io package. More of these issues will appear once we split of additional packages.

Finally is it necessary to have a jgrapht-opt package? Ideally I would prefer to optimize the default implementation. Unfortunately, there is not a one size fits all solution, so we would need a convenient way to swap out storage structures. To a certain degree, we are already doing that with the various Specifics implementations.

**Comment by jsichi** [comment]
Per the discussion above, splitting out the jgrapht-opt module is good because:

1) as you mention, there is no one-size-fits-all solution where graph representations are concerned

2) it will allow us to be more aggressive with using heavyweight dependencies in opt while keeping the core dependencies lightweight

3) as Shevek mentioned, there are cases where we can use more heavily optimized representations in cases where the application is willing to accept additional restrictions on usage

So I think we should go ahead with that split, while deferring any additional splits.

**Comment by fbraun4358** [comment]
I ran into the same problems Shevek ran into and found this discussion very helpful. Our graph is much smaller in memory, but the footprint of the graph was still an issue; we are in a limited memory environment of 2Gb and the graph was taking up over 1/4 of that.

By implementing our own Specifics for vertices and edges with optimizations for our use cases and using fastutil to save on the memory usage from java.util classes, I was able to reduce our memory footprint by ~45%.

**Comment by jsichi** [comment]
There's probably not much harm in making IntrusiveEdge public at this point; I think the hiding was only important way back when we moved connectivity from edges to graphs.

Other options would be to reference DefaultEdge instead, or define a different intrusive edge class inside the jgrapht-opt module.  I haven't thought about what the class implementations in opt would look like (and how much sharing there will be with the jgrapht-core implementations), so I don't know whether those are viable.

**Comment by d-michail** [comment]
A large part of this discussion was implemented in #593  and #633.
