### ISSUE TITLE
Graph created from ConnectivityInspector

### ISSUE THREAD

**Issue by vporton** [jgrapht/jgrapht#465]
We need to create a connectivity graph having given ConnectivityInspector.

I mean: We have a graph. Then we can create ConnectivityInspector for this graph. Next step we need to create (another) graph from ConnectivityInspector.

One use for this is if we want to compose (as in https://github.com/jgrapht/jgrapht/issues/464) a connectivity graph with another graph (I really need this in my project, it is not just an abstract idea).

Now think: Maybe we should remove ConnectivityInspector altogether and just create connectivity graph from another graph? (This would be handy, but somehow error prone, as it makes easier to confuse the original graph and its connectivity graph.)

Please discuss if ConnectivityInspector should be deprecated in the light of connectivity graph.

**Comment by vporton** [comment]
Hm, well, we may both leave (not remove) ConnectivityInspector and add connectivity graph. ConnectivityInspector may be optimized for a small number of pathExists() calls and connectivity graph is to be created when we expect many such lookups to happen at high speed, for the cost of calculating connectivity graph once.

Your thoughts?

**Comment by jkinable** [comment]
As with your previous messages: you have to be more specific: what do you want: input, expected output, processing.

Since you are only using jgrapht for 1 day, I suggest we keep ConnectivityInspector as it is now.
Here are (several) of the many options you can try:
1. Use the ConnectivityInspector#pathExistis(V u, V v). Takes O(V+E) computation time, plus O(1) lookup time for every pair (u,v). To check whether there exists a path between two vertices, all you have to do is check whether these 2 vertices are in the same connected set. This is exactly what ConnectivityInspector#pathExistis(V u, V v) does.
2. Use the StrongConnectivityInspector
3. Compute an allpairshortest path. If path cost between vertex u and vertex v = INFINITY, no path exists otherwise, a path exists. ~O(V^3)
4. Run a DFS/BFS and record which vertices you can reach.

Finally, I have no idea what you consider as a 'connectivity graph', but my guess is that this is a graph G'(V, E') where V is the set of vertices from the original graph, and E' is a set of edges, where there exists an edge (u,v) if there exists a path from u to v in the original graph. This you can easily create using ConnectivityInspector#connectedSets(). Each connectedSet forms a complete subgraph (clique). So simply add all vertices from the original graph, and create cliques for each connectedSet.

**Comment by vporton** [comment]
I see: What I call "connectivity graph" is actually called "transitive closure" and is defined in TransitiveClosure class.
