### ISSUE TITLE
High value of damping factor in PageRank

### ISSUE THREAD

**Issue by tibrewalpratik17** [jgrapht/jgrapht#497]
I was going through the implementation of PageRank matrix and I found that the value of damping factor is set to **0.85** as default while going through some of the research papers it says that it is favorable to keep it around **0.50**. These are the links of some research papers and articles which I referred to:
* [A Singular Perturbation Approach for Choosing the PageRank Damping Factor](http://www.internetmathematicsjournal.com/article/1448)
* [Ranking in evolving complex networks- Refer to page 9](https://arxiv.org/pdf/1704.08027.pdf)
* [PageRank for ranking authors in co-citation networks](http://info.slis.indiana.edu/~dingying/Publication/PageRankPreliminary.pdf)

Though this parameter can be set by the user but I think according to these papers it varies from tasks to tasks but on an average **0.50-0.55** works good.
Please let me know about your views.

**Comment by jsichi** [comment]
@d-michail can you comment on this?

**Comment by d-michail** [comment]
We use the traditional value of 0.85 which was used in the original description of the algorithm. The same is true for the number of iterations where we use 100. As you mention, depending on the graph other values might be better.

Since we are developing a library, we try to provide the tools and not optimize for every specific use-case. The constructor of the class allows the user to set both the damping factor and the number of iterations and the documentation clearly explains this. This is a standard approach used by many libraries.

**Comment by tibrewalpratik17** [comment]
@d-michail I understand but I checked the implementation of PageRank in only two other packages - 
* [NetworkX](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.link_analysis.pagerank_alg.pagerank.html)
* [iGraph](http://igraph.org/r/doc/page_rank.html)
Though they have kept their damping factor to 0.85 but in **NetworkX** the tolerance is set to _1e-06_ with max iterations as _100_. And in **igraph** the max iterations is set to _1000_ with tolerance _0.001_ . Thus by changing their default values for other parameters they are managing to get better accuracy - _increasing iterations_ or _decreasing tolerance_.
So I think we can also change some parameters to provide the user with a more optimized package as in one of the papers it was mentioned that setting a good damping factor will also make our numerical calculations faster. So we can think about changing some parametric values and if not the damping factor then we can increase iterations or decrease tolerance to provide a better algorithm.

**Comment by d-michail** [comment]
Exactly, most of the libraries set the default damping factor to 0.85 in order to have a "standard" default. Users are free to optimize by changing the parameters. The same is true for the other parameters. 

There are a lot of trade-offs when changing these parameters. Some users want speed, others want accuracy, others want numerical stability. You cannot really accommodate all.

JGraphT does not claim to contain the best PageRank implementation. There are very specialized projects for this. 

If you want to work on link analysis related to JGraphT, I would suggest to focus more on things that the library lacks such as other algorithmic variants like Personalized PageRank or even Hits.

**Comment by tibrewalpratik17** [comment]
@d-michail Thanks a lot for your explanation. I now understand that we are following a standard default and leave it to the user to set the parameters depending upon their use case.
I am working on the implementation of other algorithmic variants. At first I am planning to implement eigen-vector and alpha centrality and then move on to implement other variants such as Personalized PageRank and Hits algorithm.
