### ISSUE TITLE
Unreasonable memory usage for JohnsonShortestPaths?

### ISSUE THREAD

**Issue by simlu** [jgrapht/jgrapht#626]
I would like to replace FloydWarshallShortestPaths with [JohnsonShortestPaths.java](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/alg/shortestpath/JohnsonShortestPaths.java) since it is significant faster for my use case. While the runtime is significantly shorter, the memory consumption is unacceptable. For my input the memory usage is three times as much (6gb vs 20gb).

Is this potentially a bug in the implementation or is the memory usage expected to be this much larger? Is this due to additional vertices being created?

Thanks for helping! Much appreciated! L~

**Comment by d-michail** [comment]
Due to our requirement of not modifying the original graph, we use at least double the memory (x2). We compute a weight for each vertex using Bellman-Ford and then we also maintain new edge weights for Dijkstra. Since we have to translate back, we need to store these.

I opened up a small PR (#627) which might improve the memory consumption slightly, at least at the beginning where we execute Bellman-Ford in the augmented graph.

How does your graph look like (sparse, dense, degree distribution, etc.)?

**Comment by simlu** [comment]
@d-michail Thank you for the very quick reply and the pr! I've tested the changes but unfortunately there isn't a significant difference. I've create a test case using the following [data.txt](https://github.com/jgrapht/jgrapht/files/2191386/data.txt):

```java
@Test
    public void testLargeGraph() throws InterruptedException {
        Graph<Integer, DefaultWeightedEdge> graph = new DefaultUndirectedWeightedGraph<>(DefaultWeightedEdge.class);

        System.out.println("start");
        try {
            File f = new File("PATH/TO/DATA/FILE/data.txt");
            List<String> lines = FileUtils.readLines(f, "UTF-8");
            for (String line : lines) {
                String[] edge = line.split(" ");
                if (edge.length == 3) {
                    Graphs.addEdgeWithVertices(
                            graph, 
                            Integer.valueOf(edge[0]),
                            Integer.valueOf(edge[1]),
                            Integer.valueOf(edge[2])
                    );
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println("loaded");
        Scanner sc = new Scanner(System.in);
        Thread.sleep(5000);
        System.out.println("starting");
        long time = System.currentTimeMillis();

        ShortestPathAlgorithm<Integer, DefaultWeightedEdge> shortestPathAlgorithm = new JohnsonShortestPaths<>(graph);
        shortestPathAlgorithm.getPathWeight(0, 1);

        System.out.println("Time: " + (System.currentTimeMillis() - time));

        System.out.println("ending");
        sc.nextLine();
    }
```

Using FloydWarshallShortestPaths the memory consumption stays constant at around 126 MB (run time ~103 seconds). However when using JohnsonShortestPaths the memory creeps to 1,125 MB (run time ~6 seconds). That's 9 times more memory (!!) - not what I would expect.

Screenshots of memory breakdown below (using current master snapshot):
![john](https://user-images.githubusercontent.com/1539747/42674074-2c1a4ee6-8623-11e8-87bf-6c5cbc1b58d5.png)
_(JohnsonShortestPath, ~1,125 MB total)_

![floyd](https://user-images.githubusercontent.com/1539747/42674075-2c44c464-8623-11e8-9f9d-c469d9e8882b.png)
_(FloydWarshallShortestPaths, ~126 MB total)_

**Comment by d-michail** [comment]
The Floyd-Warshall implementation is very efficient storage-wise, using one map from vertices to integers and then only 2 arrays (with n^2 size each where n is the number of nodes). 

On the other hand, Johnson's keeps as a result a `Map<V, Map<Pair<V,Double>>` which has in total n^2 entries. As you can imagine it has the classic `HashMap.Entry` storage overhead.

I can see two possible optimizations for Johnsons: 
  - Allow the user to switch to another map. This will have a small impact, maybe save a small constant factor.
  - Keep a map from vertices to integers (just like Floyd-Warshall) and then encode Dijkstra's shortest path trees using two arrays each, instead of a `Map<Pair<V,Double>`. This should have a large impact as we are going to be paying the `HashMap.Entry` overhead only for `n` elements and not `n^2`.

I will add this to my TODO list.

**Comment by d-michail** [comment]
It turned out to be quite easy, to use the exact same representation as Floyd-Warshall. Now they should have almost identical space consumption. Could you please test #630?

**Comment by simlu** [comment]
That was super quick! Thank you so much!

I'll test tonight (PST) as I'm currently out.

**Comment by simlu** [comment]
@d-michail Still about 50% more memory recorded than Floyd, but that might be due to additional data structured that didn't get garbage collected? 

Anyways, very adequate for my purposes and great speedup! Thank you very, very much!

**Comment by d-michail** [comment]
Yes, as you mention, the additional memory used should be available to the garbage collector.

**Comment by simlu** [comment]
Sweet! Once this the pr is merged we should be ok to close this ticket. Thanks again!
