### ISSUE TITLE
fastutil: major performance improvement

### ISSUE THREAD

**Issue by simlu** [jgrapht/jgrapht#629]
Proposing to start incorporating fastutil into this project. 

Major advantages over corresponding java data structures:
- significantly reduced memory footprint (easily half or less for primitive data structures)
- significantly faster access time (again, easily half for e.g. primitive hash maps / sets)

I've been using fastutil extensively for other projects and am really impressed at how well it performs. Running into limitations when using jgrapht is very frustrating when I know ]\that they could easily be mitigated if fastutil was utilized. Overall I'm convinced that adding this dependency is going to result in a major leap in performance.

This has been discussed previously [here](https://github.com/jgrapht/jgrapht/issues/459) and briefly [here](https://github.com/jgrapht/jgrapht/pull/595#issuecomment-404667047).

The tricky part is going to be abstracting things in a way that fastutil is an optional dependency. Any suggestions how we can best accomplish this?

Let the discussion begin!

**Comment by d-michail** [comment]
We have already done a lot of work towards the direction of allowing the user to replace the underlying data structures with other implementations. We have concluded that we are going to create a separate module with specialized graph implementations. 

Some necessary preliminary work has already been done in #593. I will continue the discussion at #459 for the remaining steps.

**Comment by simlu** [comment]
Sweet! I wasn't aware this was already that far down the pipeline from the discussions I saw! Very excited to see this in action!

**Comment by simlu** [comment]
@d-michail What do you think of a custom compiled fastutil (jar) dependency that only includes some needed data structures? That would significantly reduce the size (a few hundred kb max) while still giving the benefits. We would need to put instructions on how to generate it, but using a tool like proguard it should be easy and just a config file. That way we could just use it everywhere necessary easily by putting it into core. Thoughts?

**Comment by jsichi** [comment]
We publish our artifacts to maven, so this would mean that we would also have to publish the Proguard-reduced fastutil as our own artifact, which I'd rather not do, especially since applications using JGraphT may have their own dependencies on fastutil, leading to conflicts.

I think we should start with the standard fastutil dependency isolated to jgrapht-opt.  For algorithms which want to make use of it, we can either move them out of core, or else make use of the supplier approach mentioned here:

https://groups.google.com/forum/#!topic/jgrapht-dev/rkk-X8UZmFA

(That only works for cases where a drop-in collection replacement can be used; in cases where the efficiency of using primitive-access methods is required, the only choice is to move some or all of the implementation.)

If this becomes too cumbersome, we can revisit.  For now, let's keep the core dependencies unchanged.

Independent of all that, providing a Proguard configuration+script would be useful for jgrapht-opt as well.
