### ISSUE TITLE
Hackathons?

### ISSUE THREAD

**Issue by kanishka-azimi** [jgrapht/jgrapht#701]
Are there any java or algorithm (or bioinformatics) hackathons where the jgrapht contributors meetup? I am interested in attending and contributing, if so. If not, is there any java hackathon where this should start happening in the future?

**Comment by jkinable** [comment]
Currently not. The reason being that most jgrapht developers are geographically too much dispersed. And since we are opensource we don't get money to travel. If you are interested in a hackaton which is being organized nearby where you live then you are welcome to gather some friends and build something cool. We are happy to look at project proposals.

**Comment by kanishka-azimi** [comment]
Thanks for information. I will keep getting acquainted with the basics for now. I'll try Thoughworks' bi-weekly hack night in NYC to start.
