### ISSUE TITLE
Outgoing and incoming edges in weighted graphs

### ISSUE THREAD

**Issue by max-susi** [jgrapht/jgrapht#708]
A set of edges from outgoingEdgesOf(V v) or incomingEdgesOf(V v) called on a weighted graph _(for example DirectedWeightedPseudograph)_ only contains null values.
```
Graph<String, DefaultEdge> graph = new DirectedWeightedPseudograph<String, DefaultEdge>(DefaultEdge.class);
graph.addVertex("v1");
graph.addVertex("v2");
graph.addVertex("v3");
graph.addEdge("v1", "v2");
graph.addEdge("v2", "v3");

System.out.println("outgoing:");
graph.outgoingEdgesOf("v2").stream().forEach(System.out::println);
System.out.println("incoming:");
graph.incomingEdgesOf("v2").stream().forEach(System.out::println);
```
**Output:**
```
outgoing:
(null : null)
incoming:
(null : null)
```
Same goes for other weighted graphs, such as WeightedPseudograph, WeightedMultigraph or DirectedWeightedMultigraph.

On a non weighted graph, like Pseudograph or DirectedPseudograph, everything works fine.
```
Graph<String, DefaultEdge> graph = new DirectedPseudograph<String, DefaultEdge>(DefaultEdge.class);
graph.addVertex("v1");
graph.addVertex("v2");
graph.addVertex("v3");
graph.addEdge("v1", "v2");
graph.addEdge("v2", "v3");

System.out.println("outgoing:");
graph.outgoingEdgesOf("v2").stream().forEach(System.out::println);
System.out.println("incoming:");
graph.incomingEdgesOf("v2").stream().forEach(System.out::println);
```
**Output:**
```
outgoing:
(v2 : v3)
incoming:
(v1 : v2)
```

**Comment by d-michail** [comment]
This is expected behavior, due to a small optimization that we are using. Despite the null values that you might see, the graph works fine. 

Non-weighted graphs using `DefaultEdge` as a class for the edges, store directly information on the edge. If the user uses some other class for the edge, then the graph stores the source and target inside the graph.

For weighted graph the corresponding class is called `DefaultWeightedEdge`. If you use that one then all information will be stored on the edge. If you use some other edge type (even `DefaultEdge`) then all information will be stored in the graph. Thus, If you instantiate a weighted graph with `DefaultWeightedEdge` instead of `DefaultEdge`, the `toString()` will function as you expect.

**Comment by max-susi** [comment]
I'm using DefaultWeightedEdge now and it works perfectly! Thank you for the quick reply!
