### ISSUE TITLE
DoubleLinkedList should implement List interface

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#830]
The recently introduced DoublyLinkedList should implement the List interface

**Comment by Gaurav-Punjabi** [comment]
Can I work on this issue?

**Comment by jkinable** [comment]
If you'd like, go ahead.

**Comment by d-michail** [comment]
We should probably do this before the next release. Otherwise the deprecation procedures will make this more difficult.

**Comment by jkinable** [comment]
Agreed

**Comment by HannesWell** [comment]
If @Gaurav-Punjabi is not interested anymore I could do this in the next days.

I think extending `AbstractSequentialList` should make this quite straight forward and would also safe some code. Nevertheless it will require some changes of the API of `DoublyLinkedList`. But from the comment of @d-michail and since it was not part of a release yet, I assume that this could be done without deprecation?

**Comment by jkinable** [comment]
yes, no deprecation is needed for this modification.

**Comment by HannesWell** [comment]
When going trough the code I noticed the wrapping behavior of the `ListIterator`, which I would not expect from a `java.util.List`. I assume that DoublyLinkedList should be a general purpose List now, so I think it should behave like expected and stop at each end of the list.
If this behavoiur is required by BoyerMyrvoldPlanarityInspector a separate method should be created with a special wrapping/circular iterator.

Addionally I noticed that `remove(ListNode<E>)` does not prevent the caller from removing a ListNode from another DoublyLinkedList in this instance. To prevent users from doing that I suggest to have a HashSet with all nodes in DoublyLinkedList. Remove would be still O(1) and only the nearly constant time of HashSet.remove would be added.

**Comment by d-michail** [comment]
Better to avoid the hashset. Two possible options:
 - Leave the current behaviour and document it properly
 - Make each list node be aware of the actual list it belongs (by adding a reference to the list). This way you incur the extra cost for memory but you avoid the expected O(1).

@Toptachamann What do you prefer?

Indeed, the circular behaviour can be provided with another method, perhaps `circularListIterator()`.

You will also have trouble with method `add()` which in `AbstractList` returns a boolean. So you will probably need to rename the one returning the `ListNode` to something close but different.

Moreover, you will probably need to implement the `ListIterator` methods for making the list modifiable.

**Comment by HannesWell** [comment]
Alright. I wasn't very happy with it either.
But I really like your second option. This is a good idea. This would allow to freely pass around the `ListNodes` and still enables to ensure that a `ListNode` belong at most to one list. 
In my opinion the additional memory is acceptable. We would gain safety for a low price. A double linked List in general has a higher memory footprint than a ArrayList anyway due to the extra Node-objects and their two references to their next and previous. Nevertheless a HashSet would cause much more memory cost because of the additional HashMap.Entry objects and the backing array.


I'm already working on it and generally oriented towards `java.util.LinkedList`. I replaced the calls to that `add()`-method by `addLast()` which `add()` just called. Additionally I renamed `addLast()` and `addFirst()` to `addLastNode()` and `addFirstNode()` and `getFirstElement` and `getLastElement` to `getFirst` and `getLast` in order to avoid name clashes in case you later want `DoublyLinkedList` to implement the `Deque` -interface, which `java.util.LinkedList` does. If you are interested in that, I does not look like too much work with the methods already there.

I already implemented the `ListIterator` methods. The implementation of `java.util.LinkedList` is a good help for that.

**Comment by jkinable** [comment]
@Toptachamann Could you respond to @d-michail question?

@HannesWell Are you currently working on this? What's the status? It would be great to get this done before the next release (which is already overdue). If we release now, we have to go through an annoying deprecation process which would take at least 2 releases.

**Comment by Toptachamann** [comment]
Oops, I missed this question. 

If we ever have a problem with memory footprint, we can introduce an unsafe optimized list, so it makes sense to choose the second option. 

As for the circular list iterator and other method renamings, it's fine as long we don't introduce too much complexity. The purpose of this list implementation is to make possible to use the `ListNode` references, so we might need to introduce other functionality into this implementation for other algorithms in the future.

**Comment by HannesWell** [comment]
@jkinable I'm already working on it and I'm almost done. I try to complete my work tonight and so I can submit a PR tonight.

@Toptachamann I implemented  the second option so I'm glad you share my opinion. I tried to make it a general purpose List implementation and orientated myself towards `java.util.LinkedList`. I also implemented the Deque interface because its quite easy for a linked list. This adds some code but I tried to structure the class in a way that the additional code does not really add complexity. Generally I tried to reduce the methods that contain some kind of complex logic and let the public methods just call them with the right parameters. But of course we can discuss this in the PR.
