### ISSUE TITLE
Build Graph is slower on new Version

### ISSUE THREAD

**Issue by ConsorAG** [jgrapht/jgrapht#864]
**See Details:**
[https://stackoverflow.com/questions/60042917/building-a-graph-with-jgrapht-version-0-8-2-is-faster-than-with-version-1-3-0](url)

**Steps reproduce! See eclipse Project in:**
[https://github.com/ConsorAG/JGraphTTest](url) or the 
[GraphTest.zip](https://github.com/jgrapht/jgrapht/files/4158521/GraphTest.zip)

Execute GraphBuilder. 
To Switch between the Lib Version Change the Jar File in the Build Path. The Jar Files are in the Lib directory.
I have following results with Graph over 3 Mio edges:
New Lib Version:
 took 9556 ms
 took 9987 ms
 took 9864 ms
 took 5798 ms

Old Lib Version:
 took 3013 ms
 took 4868 ms
 took 2843 ms
 took 2481 ms

Making the test using buildGraph2 instead buildGraph the results between the Lib Versions are the same!

**Comment by d-michail** [comment]
This is indeed true. There are two reasons for this: 
  - Newer graphs use a caching mechanism in order to support fast edge queries using only the two endpoints.
  - Newer graphs support edge weights without forcing the user to use class `DefaultWeightedEdge`. 
    Old versions just throw an exception if this is not the case. 

Based on the above two, we have some good and some bad news. The good news is that the caching mechanism can be disabled, by extending the graph and using the `DefaultGraphSpecificsStrategy` instead of the `FastLookupGraphSpecificsStrategy`. For example like: 

```
public class NoLookupGraph<V, E> extends AbstractBaseGraph<V, E> {

	private static final long serialVersionUID = 1L;

	public NoLookupGraph(Class<? extends E> edgeClass) {
		super(null, SupplierUtil.createSupplier(edgeClass), GraphTypeBuilder.directed().allowingMultipleEdges(true)
				.allowingSelfLoops(true).weighted(true).buildType(), new DefaultGraphSpecificsStrategy<V, E>());
	}

}
```
This will speed up the code a little. The bad news is that the second bullet cannot be disabled. Supporting weights on any type of edge class comes at a performance cost of one additional lookup on a hash table which increases graph construction time. Note that our default graph tries to capture many use cases and different uses. 

If you have special performance requirements you should consider using some graphs from our `jgrapht-opt` package which has recently acquired very specialized graph implementations, which 
support bulk loading. See our latest snapshot build and #829.

**Comment by ConsorAG** [comment]
The _NoLookupGraph_ works fine. The performance is about the same as before now. With jgraph-opt I'm not able to improve the performance:

`new FastutilMapGraph<>(null,
                                                       SupplierUtil.createDefaultEdgeSupplier(),
                                                       DefaultGraphType.directedPseudograph(),
                                                       false)`

**Comment by d-michail** [comment]
If you use the [snapshot version](https://github.com/jgrapht/jgrapht#using-via-maven) and can accept:
  - vertices and edges as integers starting from zero, 
  - a static graph after loading (you cannot add or remove anything after loading)

then `SparseIntDirectedGraph` can be bulk loaded from a list of integer pairs (from the constructor) much faster than the default graph.
