### ISSUE TITLE
SupplierUtil.createSupplier(Class) doesn't create supplier

### ISSUE THREAD

**Issue by bissim** [jgrapht/jgrapht#902]
```
 * JGraphT version: 1.4.0
 * Java version (java -version)/platform:  openjdk version "11.0.6" 2020-01-14
```

When I updated my JGraphT project dependency from 1.3.1 to 1.4.0, and after removing deprecated code, I noticed that an error still showed up while trying to import a graph from a CSV file: despite specifying a vertex supplier when a graph got created, a '_org.jgrapht.nio.ImportException: Failed to import CSV graph: Invalid vertex supplier (does not return unique vertices on each call)_' was returned to me.

It looked so strange; so, in order to exclude my project from bad coding responsibilities, I took the [CSVImporterTest.java](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-io/src/test/java/org/jgrapht/nio/csv/CSVImporterTest.java) class from this repository, I made sure it ran with no code edits, and replaced the vertex supplier provided at lines 50 and 55 from `SupplierUtil.createStringSupplier(1)` to `SupplierUtil.createSupplier(String.class)`. After these only two edits were made, the tests failed with aforementioned error.

I hope not to be in the misconception that `createSupplier(Class)` and `createStringSupplier()` methods from SupplierUtil, when the former is provided with `String` class, are intended to operate in the same way (currently, I cannot verify how `createStringSupplier()` works due to GitHub Pages maintenance).

**Steps to reproduce (small coding example)**
1. Copy `CSVImporterTest.java` class from this repository to an empty Java Maven project with due dependencies (in particular, 1.4.0 version of JGraphT ones);
2. Be sure that tests succeed by running it with no code edits;
3. Replace `SupplierUtil.createStringSupplier(1)` invocation at lines 50 and 55 with `SupplierUtil.createSupplier(String.class)`;
4. Run tests again.

**Expected behaviour**
Tests should succeed but actually fail.
As I said, I'm assuming `SupplierUtil.createStringSupplier(1)` and `SupplierUtil.createSupplier(String.class)` to have the same effect.

**Other information**
It may be also worth reporting that the Java project where I put test class in is using a Java 1.8 environment.

**Comment by d-michail** [comment]
A supplier is responsible of returning new objects each time the graph requires one. If for example a user wants to use Strings for vertices, each time she calls `graph.addVertex()` a new string should be returned. 

Calling `SupplierUtil.createSupplier(String.class)` is definitely wrong. You should never do that. It creates a supplier which just called the constructor, essentially writing `new String()` which always returns the same string. 

Calling `SupplierUtil.createStringSupplier(1)` is correct because the actual implementation keeps a count and already returns new strings.

**Comment by bissim** [comment]
I understand that.
What if I have any kind of class as argument for `createSupplier()`, including (but not limited to) `String`?

**Comment by d-michail** [comment]
Using `SupplierUtil.createSupplier(String.class)` is a bug. This is just a helper method which creates a supplier using the default constructor. It only works if the default constructor returns new objects. 
Java is well known to cache strings behind the scenes.

I do not understand the issue here.  Perhaps our documentation is somewhat misleading.

If you want to create your own string supplier which does not use a counter but uses some other method to create unique strings each time it is invoked, you are free to do so.

**Comment by bissim** [comment]
Hello @d-michail and thank you for your answer.

Indeed, this is not an issue with library then, just a misunderstanding of mine about suppliers: I thought they were also needed when a graph is imported from a file.

I filed a [proper help request](https://stackoverflow.com/questions/61089620/) on StackOverflow and now I can close this issue.

Sorry for bothering about such a trivial request.
