### ISSUE TITLE
License for port to another language?

### ISSUE THREAD

**Issue by ChuckJonas** [jgrapht/jgrapht#903]
_Sorry if this is not the right place to ask..._

We're working on a Hopcroft-Karp implementation for Salesforce's Apex language.

We heavily derived from [this class](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-core/src/main/java/org/jgrapht/alg/matching/HopcroftKarpMaximumCardinalityBipartiteMatching.java) (we've cited the original authors copyright in the work).

I wasn't sure which license it needed to be released under...

Because it's duel licensed, do I need to release under EPL or LGPL?

I would prefer to release it as MIT as it is more permissive....

**Comment by jsichi** [comment]
Hello and thanks for checking with us...we appreciate it!

In general, when you create a derivative work from JGraphT code, you're required to redistribute it under your choice of either EPL or LGPL (or both).  Since these are weak copyleft licenses, it's not OK to redistribute under a more permissive license such as MIT.

In this particular case, the code isn't huge, is self-contained, and was written by a single author, Joris Kinable (the changes by other authors appear to be cosmetic).  So you could ask him for his permission to redistribute your derived work under a different license, and it would be up to him to decide.  Tagging in @jkinable for this.

I'm not a lawyer, you should be sure to get the opinion of one regardless of what you read here, etc etc

**Comment by ChuckJonas** [comment]
@jsichi thank you for clarifying... Licensing is always confusing. I'll go with EPL as it seems to be a little more open (honestly not sure), unless I hear back from the original author.

Will go ahead and close out.  Thanks

**Comment by jkinable** [comment]
@ChuckJonas thanks for asking! I'm fine with the port of our code into the Salesforce's Apex language. Please include a reference to both the original author (me) and the JGraphT library.

**Comment by ChuckJonas** [comment]
I wish we could do a true port!

Unfortunately apex is missing too many language features (we don't even have use of generic outside of system collections).

I've credited/copyrighted you & jgrapht in the readme and the class we borrowed heavily from.

https://github.com/ChuckJonas/apex-hopcroft-karp

Happy to change/add anything if needed.

Thanks!
