### ISSUE TITLE
404 link to documentation

### ISSUE THREAD

**Issue by sguermond** [jgrapht/jgrapht#948]
```
 * JGraphT version: n/a
 * Java version (java -version)/platform: n/a
```

**Issue**
https://jgrapht.org/guide/UserOverview leads to a 404.

**Steps to reproduce (small coding example)**
1. Go to jgrapht.org
2. Scroll to Documentation section
3. Click on User Guide

**Expected behaviour**
Being able to access the documentation site.

**Other information**

**Comment by jsichi** [comment]
Oof, something must have gone wrong with the last automated deployment...taking a look now.

**Comment by jsichi** [comment]
Since a93d490da65bff9890418667200021e41ab6c793, Travis logs indicate it's been failing like this:

```
1.59s$ if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then etc/prepareDocs.sh; fi
~/build/jgrapht/jgrapht/docs/guide-templates ~/build/jgrapht/jgrapht
Expanding GuavaAdapter.md to /home/travis/build/jgrapht/jgrapht/docs/guide/GuavaAdapter.md
/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/hercule/node_modules/got/dist/source/create.js:133
    const paginateEach = (async function* (url, options) {
                                        ^
SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/hercule/node_modules/got/dist/source/index.js:7:18)
```

I don't think it was anything about that particular change, so probably something environmental going on with Travis.  I'll investigate that, and also figure out how to keep errors like this from being squelched when they occur in the future.

**Comment by jsichi** [comment]
From the timing (2 days) ago probably this change to hercule:  https://github.com/jamesramsay/hercule/pull/487

We should probably be locking in a specific node version, as well as a specific hercule build if possible.

**Comment by jsichi** [comment]
OK, fixed it by telling nvm to use node lts version.  I also sprinkled in a few set -e directives so that if this happens again in the future, the build will fail instead of pushing missing docs.  Should still probably lock node and hercule versions, so I'm going to create a separate issue for that.

If the docs don't show up yet, use this link to bypass the CDN:

https://jgrapht.org/guide/UserOverview?version=xyz

Thanks for reporting!

**Comment by jsichi** [comment]
Aaaaaand note #950
