### ISSUE TITLE
released zip doesn't include jar files

### ISSUE THREAD

**Issue by albertnetymk** [jgrapht/jgrapht#969]
On the release page (https://github.com/jgrapht/jgrapht/releases), the zip file contains the source instead of the built jar files. In contrast, the zip file downloaded from https://sourceforge.net/projects/jgrapht/ contains the lib file. I wonder if this inconsistency is intended. IMO, placing the built jar files in the released zip makes more sense.

**Comment by jsichi** [comment]
The github release process is painful when done manually:

https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

So we never really did anything with it explicitly; github creates the source archive automatically as a side effect when we run the maven release process.  (@jkinable correct me if I'm wrong about this.)  We could upload the binary archive here (as we do for the sourceforge release), but for now we'll probably just stick with the old sourceforge stuff since it provides better download analytics, and our entire history remains there.

**Comment by albertnetymk** [comment]
I see; thank you for the explanation.
