### ISSUE TITLE
addEdge method stores a second instance of a vertex

### ISSUE THREAD

**Issue by marcelocenerine** [jgrapht/jgrapht#98]
I have experienced an issue that took me a while to figure out what was going on. I confess that it was caused by my code, but possibly you guys may consider that it could be handled internally by JGraphT.

Given:

```
obj1
obj2
obj3

obj2.equals(obj3) => true
obj2 == obj3 => false
```

If I add the first two to a DirectedAcyclicGraph:

```
graph.addVertex(obj1)
graph.addVertex(obj2)
```

And create an edge between obj1 and obj3 (which is not the same reference to the object in the graph, but is equal):

```
graph.addEdge(obj1, obj3)
```

When I want to find obj2...

- by getting the elements in the graph calling graph.vertexSet() or traversing the graph using an iterator (TopologicalOrderIterator) ; and
- by getting the edges of obj1:

```
Set<DefaultEdge> edges = graph.outgoingEdgesOf(obj1)
[for...]
graph.getEdgeTarget(edge)
```

I get two different instances (obj2 and obj3), as the graph stores the object passed in to the addEdge method in a secondary data structure (it only ensures that the informed object is in the graph, but does not create the edge using the existing instance).

Is this behaviour something expected in JGraphT or something that could be avoided if the edge was created using the objects stored in the graph, not the ones passed in the method addEdge?

Thanks,

Marcelo

**Comment by TAKeanice** [comment]
We had that problem while implementing the VF2 Algorithm on JGraphT Objects, too. Solution of course was just to use `.equals()` instead of `==`. I think the current implementation is legit, as it gives you more flexibility. If you needed to get a reference to the vertex object every time, instead of just accessing it through a string or integer that you get from somewhere, everything would be much less elegant. If you want, you can use the actual vertices as sources and targets of your edge, then `==` succeeds! If you use different instances, just do `.equals()`

**Comment by jsichi** [comment]
This is expected behavior.  Either you rely on object identity for vertices and edges (in which case you  should take care to avoid using objects for which equals and == differ), or you don't (in which case your code shouldn't care).
