### ISSUE TITLE
AbstractGraph's hashCode() implementation is incoherent with equals() on undirected graphs

### ISSUE THREAD

**Issue by vigna** [jgrapht/jgrapht#990]
```
 * JGraphT version: 1.5
 * Java version (java -version)/platform:  java version "13.0.1" 2019-10-15 Mac OS X
```

**Issue**

AbstractGraph's hashCode() will return different hash codes for equal graphs. As an alternative interpretation of the failing test below, the Guava adapters do not implement properly getEdgeSource()/getEdgeTarget().

**Steps to reproduce (small coding example)**

```
package org.jgrapht.webgraph;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.jgrapht.graph.guava.MutableGraphAdapter;
import org.junit.jupiter.api.Test;

import com.google.common.graph.GraphBuilder;
import com.google.common.graph.MutableGraph;


class AbstractGraphTest {

	@Test
	void testUndirectedEquality() {
		final MutableGraph<Integer> g = GraphBuilder.undirected().build();
		g.putEdge(0, 1);

		final MutableGraph<Integer> h = GraphBuilder.undirected().build();
		h.putEdge(1, 0);
		assertEquals(new MutableGraphAdapter<>(g), new MutableGraphAdapter<>(h));
		assertEquals(new MutableGraphAdapter<>(g).hashCode(), new MutableGraphAdapter<>(h).hashCode());
	}
}
```

**Expected behaviour**

If two graphs are equal, they should have the same hash code. The problem lies in the usage of an order-sensitive pairing function in AbstractGraph.hashCode(), or in the lack of implementation in the adapter of the (a bit cryptic) statement 

     For an undirected graph, source and target are distinguishable designations (but without any mathematical meaning).

in the documentation of Graph. If the above is meaning that the undirected edge {0,1} must _always_ have source 0 and target 1, say (or vice versa) even if that does not have a mathematical meaning, then the problem is in the adapter, rather than in AbstractGraph.hashCode(), and BaseGraphAdapter.getEdgeSource() should be reimplemented as returning the, say, minimum between nodeU() and nodeV() (the dual for getEdgeTarget()).

**Comment by vigna** [comment]
BTW, this test shows what I mean about the statement in the documentation and the adapter:

```
	@Test
	void testEdgeCoherence() {
		final MutableGraph<Integer> g = GraphBuilder.undirected().build();
		g.putEdge(0, 1);

		final MutableGraph<Integer> h = GraphBuilder.undirected().build();
		h.putEdge(1, 0);
		final MutableGraphAdapter<Integer> a = new MutableGraphAdapter<>(g);
		final MutableGraphAdapter<Integer> b = new MutableGraphAdapter<>(h);
		assertEquals(a.getEdgeSource(a.getEdge(0, 1)), b.getEdgeSource(b.getEdge(1, 0)));
	}

```

**Comment by jsichi** [comment]
This is subtle.  Guava defines two unordered endpoint pairs as equal even when they have u/v swapped.  Guava's design decision in this case is curious in that it allows for two equal objects which have distinguishable attributes (a size-2 set would be more appropriate than a pair).  But c'est la vie.

Our graph.equals implementation assumes that if e1.equals(e2), and g1 contains e1, and g2 contains e2, then for graph equality to hold, source(g1,e1) should be equal to source(g2.e2).  And likewise for target.  This assumption is reasonable-ish but unstated, and glossed over as "having identical edge sets".

Our adapter violates this assumption since it uses unordered endpoint pairs as edges.  In the example, the two edges in the two graphs are equal but have u/v flipped.  Since we've mapped source to u and target to v, the result is the noted anomaly.

Fix (a) is what @vigna suggested:  treat this as a bug in the adapter, and use min/max to map (u,v)->(source,target).  This is problematic since it requires the vertices to be orderable.  (I don't think we can rely on hash code comparison due to the possibility of collisions.)

Fix (b) is to treat the assumption as incorrect in the case of undirected graphs, meaning for undirected graphs we should change the corresponding implementations of equals/hashCode to treat edge source/target as symmetric.  This seems like a good improvement anyway.  If we ever get around to fully supporting mixed graphs, we would need to get this classification from the edge, but for now we can just use the graph type.

@d-michail and others, opinions?

Whatever happens, this page is probably due for an update regarding the assumption above:

https://github.com/jgrapht/jgrapht/wiki/Users%3A-EqualsAndHashCode

**Comment by vigna** [comment]
Note that I'm working on a low-memory implementation of the WebGraph adapter (that's why I'm filing this reports—I'm trying to learn how to write it properly from your code so I'm digging deep) and I think that having edges which do not implement equals() is useful, given that the user is made aware. I've seen this happens in JGraphT, too. In particular I'd like to have a low-memory adapter using arrays of two elements as that uses less than half memory than an EndpointPair<Integer>.

On the other hand, one might assume that the vertices have a total order. This is not unreasonable because otherwise, for instance, there is not even a defined vertex enumeration order, and this means that in principle different executions of the same algorithm might give different results—something pernicious. The vertex enumeration order might be buried deep into getEdgeSource()/getEdgeTarget(). What I mean is that there is no need to make the type E implement comparable—due to JGraphT design, it is sufficient that the graph class knows how to implement it.

**Comment by d-michail** [comment]
I guess for the `hashCode` we should simply compute the sum of the hash codes instead of the pairing function.  I am also in favor of adding different implementations based on the graph type for the `equals` method.

For the `MutableGraphAdapter` is already works correctly, mostly because we compare `getEdgeSource(e)` with `g.getEdgeSource(e)` which both return the same result as they read it directly from the edge which is `EndpointPair`.

Regarding the edge coherence tests, I am not really sure how to fix this. Note that even the following fails: 

```
    @Test
    public void testEdgeCoherenceSameGraph() {
        final MutableGraph<Integer> g = GraphBuilder.undirected().build();
        g.putEdge(0, 1);

        final MutableGraphAdapter<Integer> a = new MutableGraphAdapter<>(g);
        
        EndpointPair<Integer> e1 = a.getEdge(0, 1);
        EndpointPair<Integer> e2 = a.getEdge(1, 0);
        
        assertEquals(e1, e2);
        assertEquals(a.getEdgeSource(e1), a.getEdgeSource(e2));
    }
```

I can see three different ways here:
  - What @vigna suggested, adding a total order inside the adapter (probably some Map<V, Integer>). The drawbacks here are the extra space cost and the extra hashtable lookup for each `getEdgeSource()` or `getEdgeTarget()`.
  - Switching to our own edge implementation instead of using the `EndpointPair<V>` 
  - Do not do anything and document this strange behavior in the adapters.

**Comment by jsichi** [comment]
For solution (a), we could change the adapter to take an optional Comparator.  If none was supplied, we would attempt to use the natural ordering (if the vertex type implements Comparable), otherwise the adapter would maintain a Vertex->Long mapping internally.

For solution (b), all we have to do is change the AbstractGraph equals/hashCode to treat source/target as symmetric for undirected graphs (matching Guava's u/v semantics).

@vigna, regarding repeatable iteration order:  In JGraphT we leave this decision up to the graph implementation; i.e. the interface doesn't guarantee it, but implementations are free to do so.  Our default graph implementations provide this guarantee via use of LinkedHashXXX classes when building our internal data structures, resulting in insertion order as the repeatable order.

Guava goes as far as leaving this to be controlled by the user (choosing between no order, insertion order, natural order, and custom order), which is nice: 

https://guava.dev/releases/23.0/api/docs/com/google/common/graph/GraphBuilder.html#nodeOrder-com.google.common.graph.ElementOrder-

We could do the same for the WebGraph adapter if it makes sense (regardless of whether we choose solution a or b for the anomaly).

**Comment by jsichi** [comment]
I've updated the wiki page.
